development:
  adapter: mysql
  database: dobremaszyny_development
  username: railsuser
  password: railspass
  host: localhost
  socket: /tmp/mysql.sock
  #/var/run/mysqld/mysqld.sock
  
test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

production:
  adapter: mysql
  database: kuzniarp_dobremaszyny
  username: kuzniarp
  password: mPLX8XbpFjbqR9VG
  host: db01.openetworks.pl
